def version() -> str: ...
def evaluate(cards: str) -> int: ...
def hand_category(value: int) -> str: ...
def range_combos(text: str, dead: str = "") -> list[tuple[str, float]]: ...
def range_grid(text: str) -> list[float]: ...
def hand_class_names() -> list[str]: ...

class HandStrength:
    @property
    def win(self) -> float: ...
    @property
    def tie(self) -> float: ...
    @property
    def lose(self) -> float: ...
    @property
    def combos(self) -> float: ...

def hand_strength(hero: str, villain: str, board: str, dead: str = "") -> HandStrength: ...

class PlayerEquity:
    @property
    def equity(self) -> float: ...
    @property
    def win(self) -> float: ...
    @property
    def tie(self) -> float: ...
    @property
    def lose(self) -> float: ...
    @property
    def std_error(self) -> float: ...

class EquityResult:
    @property
    def players(self) -> list[PlayerEquity]: ...
    @property
    def exact(self) -> bool: ...
    @property
    def samples(self) -> int: ...
    @property
    def seed(self) -> int: ...

def equity(
    players: list[str],
    board: str = "",
    dead: str = "",
    *,
    mode: str = "auto",
    iterations: int = 200_000,
    exact_limit: float = 3e7,
    seed: int = 0,
) -> EquityResult: ...
